export enum INQUIRY_TYPES {
  OPEN_ACCOUNT = 'OPEN_ACCOUNT',
  INFORMATION_CURRENCY = 'INFORMATION_CURRENCY',
  CASH_BALANCE = 'CASH_BALANCE',
  FILE_CABINET = 'FILE_CABINET',
  ACCOUNT_RESTRICTION = 'ACCOUNT_RESTRICTION',
}
